# Generated by Django 4.2.8 on 2024-01-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Daily",
            fields=[
                (
                    "postnum",
                    models.BigAutoField(
                        db_column="postNum", primary_key=True, serialize=False
                    ),
                ),
                ("total_meal_calories", models.FloatField(blank=True, null=True)),
                ("total_exercise_calories", models.FloatField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("current_weight", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "daily",
                "managed": False,
            },
        ),
    ]
