# Generated by Django 4.2.8 on 2024-01-22 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0002_daily"),
        ("users_app", "0002_usersappuser"),
    ]

    operations = []
