# Generated by Django 4.2.8 on 2024-01-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdditionalFoodInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_code", models.TextField(blank=True, null=True)),
                ("food_name", models.TextField(blank=True, null=True)),
                ("maker", models.TextField(blank=True, null=True)),
                ("major_class", models.TextField(blank=True, null=True)),
                ("detail_class", models.TextField(blank=True, null=True)),
                (
                    "one_serve_amount_g_field",
                    models.FloatField(
                        blank=True, db_column="one_serve_amount(g)", null=True
                    ),
                ),
                (
                    "total_amount_g_field",
                    models.FloatField(
                        blank=True, db_column="total_amount(g)", null=True
                    ),
                ),
                ("calories", models.FloatField(blank=True, null=True)),
                ("water", models.FloatField(blank=True, null=True)),
                ("protein", models.FloatField(blank=True, null=True)),
                ("fat", models.FloatField(blank=True, null=True)),
                ("carbohydrate", models.FloatField(blank=True, null=True)),
                ("suger", models.FloatField(blank=True, null=True)),
                ("dietary_fiber", models.FloatField(blank=True, null=True)),
                ("natrium", models.FloatField(blank=True, null=True)),
                ("total_sfa", models.FloatField(blank=True, null=True)),
                ("total_tfa", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "additional_food_info",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CalorieDictAllProcessed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_code", models.TextField(blank=True, null=True)),
                ("food_name", models.TextField(blank=True, null=True)),
                ("maker", models.TextField(blank=True, null=True)),
                ("major_class", models.TextField(blank=True, null=True)),
                ("detail_class", models.TextField(blank=True, null=True)),
                (
                    "one_serve_amount_g_field",
                    models.FloatField(
                        blank=True, db_column="one_serve_amount(g)", null=True
                    ),
                ),
                (
                    "total_amount_g_field",
                    models.FloatField(
                        blank=True, db_column="total_amount(g)", null=True
                    ),
                ),
                ("calories", models.FloatField(blank=True, null=True)),
                ("water", models.FloatField(blank=True, null=True)),
                ("protein", models.FloatField(blank=True, null=True)),
                ("fat", models.FloatField(blank=True, null=True)),
                ("carbohydrate", models.FloatField(blank=True, null=True)),
                ("suger", models.FloatField(blank=True, null=True)),
                ("dietary_fiber", models.FloatField(blank=True, null=True)),
                ("natrium", models.FloatField(blank=True, null=True)),
                ("total_sfa", models.FloatField(blank=True, null=True)),
                ("total_tfa", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "calorie_dict_all_processed",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CalorieDictionary",
            fields=[
                (
                    "food_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("food_name", models.CharField(max_length=100)),
                ("maker", models.CharField(max_length=100)),
                ("major_class", models.CharField(max_length=50)),
                ("detail_class", models.CharField(max_length=50)),
                (
                    "one_serve_amount_g_field",
                    models.FloatField(
                        blank=True, db_column="one_serve_amount(g)", null=True
                    ),
                ),
                (
                    "total_amount_g_field",
                    models.FloatField(
                        blank=True, db_column="total_amount(g)", null=True
                    ),
                ),
                ("calories", models.FloatField(blank=True, null=True)),
                ("water", models.FloatField(blank=True, null=True)),
                ("protein", models.FloatField(blank=True, null=True)),
                ("fat", models.FloatField(blank=True, null=True)),
                ("carbohydrate", models.FloatField(blank=True, null=True)),
                ("suger", models.FloatField(blank=True, null=True)),
                ("dietary_fiber", models.FloatField(blank=True, null=True)),
                ("natrium", models.FloatField(blank=True, null=True)),
                ("total_sfa", models.FloatField(blank=True, null=True)),
                ("total_tfa", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "calorie_dictionary",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "postnum",
                    models.BigIntegerField(
                        db_column="postNum", primary_key=True, serialize=False
                    ),
                ),
                ("meal_date", models.DateTimeField(blank=True, null=True)),
                ("meal_photo", models.CharField(blank=True, max_length=255, null=True)),
                ("meal_info", models.TextField(blank=True, null=True)),
                ("meal_type", models.CharField(blank=True, max_length=20, null=True)),
                ("meal_calories", models.FloatField(blank=True, null=True)),
                ("nutrient_info", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "meal",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UsersAppUser",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
                ("user_age", models.DateField(blank=True, null=True)),
                ("user_gender", models.IntegerField(blank=True, null=True)),
                ("user_height", models.FloatField(blank=True, null=True)),
                ("user_weight", models.FloatField(blank=True, null=True)),
                (
                    "user_activity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("user_daily_calorie", models.IntegerField(blank=True, null=True)),
                ("user_target_weight", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "users_app_user",
                "managed": False,
            },
        ),
    ]
