# Generated by Django 4.2.8 on 2024-01-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalFoodInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_code", models.TextField(blank=True, null=True)),
                ("food_name", models.TextField(blank=True, null=True)),
                ("maker", models.TextField(blank=True, null=True)),
                ("major_class", models.TextField(blank=True, null=True)),
                ("detail_class", models.TextField(blank=True, null=True)),
                (
                    "one_serve_amount_g_field",
                    models.FloatField(
                        blank=True, db_column="one_serve_amount(g)", null=True
                    ),
                ),
                (
                    "total_amount_g_field",
                    models.FloatField(
                        blank=True, db_column="total_amount(g)", null=True
                    ),
                ),
                ("calories", models.FloatField(blank=True, null=True)),
                ("water", models.FloatField(blank=True, null=True)),
                ("protein", models.FloatField(blank=True, null=True)),
                ("fat", models.FloatField(blank=True, null=True)),
                ("carbohydrate", models.FloatField(blank=True, null=True)),
                ("suger", models.FloatField(blank=True, null=True)),
                ("dietary_fiber", models.FloatField(blank=True, null=True)),
                ("natrium", models.FloatField(blank=True, null=True)),
                ("total_sfa", models.FloatField(blank=True, null=True)),
                ("total_tfa", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "additional_food_info",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CalorieDictAllProcessed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_code", models.TextField(blank=True, null=True)),
                ("food_name", models.TextField(blank=True, null=True)),
                ("maker", models.TextField(blank=True, null=True)),
                ("major_class", models.TextField(blank=True, null=True)),
                ("detail_class", models.TextField(blank=True, null=True)),
                (
                    "one_serve_amount_g_field",
                    models.FloatField(
                        blank=True, db_column="one_serve_amount(g)", null=True
                    ),
                ),
                (
                    "total_amount_g_field",
                    models.FloatField(
                        blank=True, db_column="total_amount(g)", null=True
                    ),
                ),
                ("calories", models.FloatField(blank=True, null=True)),
                ("water", models.FloatField(blank=True, null=True)),
                ("protein", models.FloatField(blank=True, null=True)),
                ("fat", models.FloatField(blank=True, null=True)),
                ("carbohydrate", models.FloatField(blank=True, null=True)),
                ("suger", models.FloatField(blank=True, null=True)),
                ("dietary_fiber", models.FloatField(blank=True, null=True)),
                ("natrium", models.FloatField(blank=True, null=True)),
                ("total_sfa", models.FloatField(blank=True, null=True)),
                ("total_tfa", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "calorie_dict_all_processed",
                "managed": False,
            },
        ),
    ]
