# Generated by Django 4.2.8 on 2024-01-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("menu_id", models.AutoField(primary_key=True, serialize=False)),
                ("menu_type", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "menu_classification",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("menu_dtl", models.CharField(blank=True, max_length=100, null=True)),
                ("calories", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "menu",
                "managed": False,
            },
        ),
    ]
